### ISSUE TITLE
Figure out how to alert when addListener is used inappropriately with a GenericEvent

### ISSUE THREAD

**Issue by cpw** [MinecraftForge/EventBus#10]
addListener with a GenericEvent subclass is missing the generic event filter, causing the event to fire for all events.

See MinecraftForge/MinecraftForge#5387

**Comment by pau101** [comment]
One possibility would be to utilize the compiler's behavior with [method specificity](https://docs.oracle.com/javase/specs/jls/se8/html/jls-15.html#jls-15.12.2.5) such that typical calls, which result in `addListener` with a `Consumer<? extends GenericEvent<?>>`, are resolved to a failure function.

If there is an overload to the existing `addListener(Consumer<T>)` such as:
```java
@FunctionalInterface
public interface GenericConsumer<T extends GenericEvent<?>> extends Consumer<T> {}

/**
 * Use {@link #addGenericListener} to receive GenericEvents
 */
@Deprecated
public <T extends GenericEvent<?>> void addListener(final GenericConsumer<T> consumer) {
	throw new IllegalArgumentException("Use EventBus.addGenericListener to receive GenericEvents");
}
```
The following calls resolve to it:
```java
addListener((RegistryEvent.Register<Block> event) -> {});
addListener(this::onRegister); // void onRegister(final RegistryEvent.Register<Block> event)
addListener(event -> {})
addListener(this::onEvent); // void onEvent(final Event event)
addListener(null);
```
And the following to existing `addListener(Consumer<T>)`:
```java
addListener((RegistryEvent.NewRegistry event) -> {});
addListener(this::onNewRegistry); // void onNewRegistry(final RegistryEvent.NewRegistry event)
addListener((Event event) -> {});
addListener((Consumer<Event>);  // void onEvent(final Event event)
```
A generic listener that that goes undetected from resolving to existing `addListener(Consumer<T>)`:
```java
addListener((Consumer<? extends Event>) (RegistryEvent.Register<Block> event) -> {});
```
A generic listener that could be caught while resolving to existing `addListener(Consumer<T>)` if raw argument was inspected as currently done for `Event` equality, but for  `GenericEvent` assignablity:
```java
addListener(new MyRegisterListener()) // class MyRegisterListener implements Consumer<RegistryEvent.Register<Block>> 
```
