### ISSUE TITLE
Error Launching MC 1.14.3 + Forge 27.0.25

### ISSUE THREAD

**Issue by JonnyBrando** [MinecraftForge/EventBus#31]
Unable to download re-requisite librararies:

Failed to download file.
Name: eventbus-0.10.3-milestone.0.1+1a5fa31-service.jar
URL: https://modloaders.forgecdn.net/647622546/maven/net/minecraftforge/eventbus/0.10.3-milestone.0.1+1a5fa31-service/eventbus-0.10.3-milestone.0.1+1a5fa31-service.jar
Error details: The requested URL returned error: 403 Forbidden
Filename on disk: eventbus-0.10.3-milestone.0.1+1a5fa31-service.jar
Path: C:\Users\jbruneau\Twitch\Minecraft\Install\libraries\net\minecraftforge\eventbus\0.10.3-milestone.0.1+1a5fa31-service\eventbus-0.10.3-milestone.0.1+1a5fa31-service.jar
Exists: Nonexistent

Accessing the URL in Google Chrome:

(Error)
(Code)AccessDenied(/Code)
(Message)Access Denied(/Message)
(RequestId)76B6FEECF7DC890D(/RequestId)
(HostId)
9InSbQL46MY9DjXXhq3Y6JvrGxy6E9YW9kL2xY/mJewFxLAWoA5FURhSQgGj1vNot2s5JliM0d4=
(/HostId)
(/Error)

**Comment by DaemonUmbra** [comment]
Next time try the forums first.
Also this is a Twitch/CurseForge CDN issue, not a Forge issue.
