### ISSUE TITLE
Support JarInJar event registration

### ISSUE THREAD

**Issue by bloodmc** [MinecraftForge/EventBus#47]
I am currently working on adding Forge support for my mod GriefDefender and am unable to register events on the Forge event bus when calling `MinecraftForge.EVENT_BUS` from within my jarinjar. 

Here are the errors I receive : 

https://gist.github.com/bloodmc/7cac83645c015973a5065fedd5b1a884

Any way to add support for event registration for jarinjar mods?

[LuckPerms](https://github.com/LuckPerms/LuckPerms/tree/master/forge) also requires this but has added a workaround for the time being.

Thanks!

**Comment by LexManos** [comment]
Any issues caused by JarInJar should be reported to JarInJar. From the rest of the world it should just be another file system.

**Comment by bloodmc** [comment]
I should of been more clear, I'm actually using Luck's jarinjar implementation. As he added a workaround, I will just use that. Thanks!
