### ISSUE TITLE
Listeners being registered as null

### ISSUE THREAD

**Issue by OhYea777** [MinecraftForge/EventBus#8]
There appears to be an edge case where it is passing a null reference to the registration in **ListenerListInst**. I have written unit test to reproduce the error along with the error output I had when running said test: https://gist.github.com/OhYea777/82bd5880f436f7ef2393a32fbdfd54ad

**Note**: due to the nature of the issue, it does not always throw an error, in this case the test needs to be ran numerous times before it fails

**Comment by cpw** [comment]
Thanks for this, I found the problem and fixed it I think..
